image: openjdk:8-jdk

variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/Overlord-1.11.2-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/Overlord-1.11.2-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- deploy
    
deploy:
  stage: deploy
  script:
  - ./gradlew clean
  - ./gradlew build uploadArchives curseforge uploadToModsIO -PcurseForgeApiKey=$curseForgeApiKey -PmodsioApiKey=$modsioApiKey --stacktrace
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "Overlord-1.11.2-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
